a = input("Введите имя:")
b = input("Введите фамилию:")
objective = input("Ваша должность:")
education = input("Ваше образование:")
experience = input("Опыт работы:")
print(a, b)
print("OBJECTIVE:")
print(objective)
print("EDUCATION:")
print(education)
print("EXPERIENCE:")
print( experience)

